Started logging messages at Sun Sep 24 18:18:47 2023
Info:    Using UV tolerance 1e-06
Info:    Using UV tolerance 1e-06
Info:    HwNlibToTSLib options selected:
Info:        Points: On
Info:        Curves: On
Info:        Surfaces: Off
Info:        BReps: On
Info:        Do not create IwAssembly/IwAssemblyInstance objects
Info:        Making untrimmed surfaces into BReps
Info:        Making solids into single BReps
Info:        Make components of failed trims
Info:        Make faces of failed B-reps
Info:    HW SAT v1.2.6-maint
Info:    Reading 
Info:    Processing 
Info:    Transferring 
Info:    
Info:    Found 0 points in file
Info:    Found 0 curves in file
Info:    Found 0 surfaces in file
Info:    Found 0 trimmed surfaces in file
Info:    Found 1 B-reps in file
Info:    Found 224 B-rep faces in file
Info:    
Info:    Using 3D tolerance 1e-06
Info:    Working on 0
Info:        Working on 71
Info:            Created 
Info:        Working on 72
Info:            Created 
Info:        Working on 100
Info:            Created 
Info:        Working on 101
Info:            Created 
Info:        Working on 8
Info:            Created 
Info:        Working on 92
Info:            Created 
Info:        Working on 135
Info:            Created 
Info:        Working on 12
Info:            Created 
Info:        Working on 132
Info:            Created 
Info:        Working on 185
Info:            Created 
Info:        Working on 17
Info:            Created 
Info:        Working on 182
Info:            Created 
Info:        Working on 257
Info:            Created 
Info:        Working on 26
Info:            Created 
Info:        Working on 254
Info:            Created 
Info:        Working on 366
Info:            Created 
Info:        Working on 45
Info:            Created 
Info:        Working on 363
Info:            Created 
Info:        Working on 528
Info:            Created 
Info:        Working on 76
Info:            Created 
Info:        Working on 525
Info:            Created 
Info:        Working on 749
Info:            Created 
Info:        Working on 116
Info:            Created 
Info:        Working on 746
Info:            Created 
Info:        Working on 1021
Info:            Created 
Info:        Working on 166
Info:            Created 
Info:        Working on 1018
Info:            Created 
Info:        Working on 1331
Info:            Created 
Info:        Working on 238
Info:            Created 
Info:        Working on 1328
Info:            Created 
Info:        Working on 1665
Info:            Created 
Info:        Working on 347
Info:            Created 
Info:        Working on 1662
Info:            Created 
Info:        Working on 1984
Info:            Created 
Info:        Working on 509
Info:            Created 
Info:        Working on 1981
Info:            Created 
Info:        Working on 2255
Info:            Created 
Info:        Working on 730
Info:            Created 
Info:        Working on 2252
Info:            Created 
Info:        Working on 2467
Info:            Created 
Info:        Working on 1002
Info:            Created 
Info:        Working on 2084
Info:            Created 
Info:        Working on 2470
Info:            Created 
Info:        Working on 1312
Info:            Created 
Info:        Working on 1773
Info:            Created 
Info:        Working on 2260
Info:            Created 
Info:        Working on 1646
Info:            Created 
Info:        Working on 1436
Info:            Created 
Info:        Working on 1991
Info:            Created 
Info:        Working on 1968
Info:            Created 
Info:        Working on 1113
Info:            Created 
Info:        Working on 1672
Info:            Created 
Info:        Working on 1777
Info:            Created 
Info:        Working on 828
Info:            Created 
Info:        Working on 1338
Info:            Created 
Info:        Working on 1440
Info:            Created 
Info:        Working on 590
Info:            Created 
Info:        Working on 1028
Info:            Created 
Info:        Working on 1117
Info:            Created 
Info:        Working on 409
Info:            Created 
Info:        Working on 756
Info:            Created 
Info:        Working on 832
Info:            Created 
Info:        Working on 286
Info:            Created 
Info:        Working on 535
Info:            Created 
Info:        Working on 594
Info:            Created 
Info:        Working on 212
Info:            Created 
Info:        Working on 373
Info:            Created 
Info:        Working on 413
Info:            Created 
Info:        Working on 155
Info:            Created 
Info:        Working on 196
Info:            Created 
Info:        Working on 290
Info:            Created 
Info:        Working on 146
Info:            Created 
Info:        Working on 329
Info:            Created 
Info:        Working on 330
Info:            Created 
Info:        Working on 565
Info:            Created 
Info:        Working on 564
Info:            Created 
Info:        Working on 200
Info:            Created 
Info:        Working on 465
Info:            Created 
Info:        Working on 800
Info:            Created 
Info:        Working on 274
Info:            Created 
Info:        Working on 676
Info:            Created 
Info:        Working on 1086
Info:            Created 
Info:        Working on 397
Info:            Created 
Info:        Working on 945
Info:            Created 
Info:        Working on 1409
Info:            Created 
Info:        Working on 578
Info:            Created 
Info:        Working on 1255
Info:            Created 
Info:        Working on 1750
Info:            Created 
Info:        Working on 816
Info:            Created 
Info:        Working on 1589
Info:            Created 
Info:        Working on 2065
Info:            Created 
Info:        Working on 1101
Info:            Created 
Info:        Working on 1913
Info:            Created 
Info:        Working on 2319
Info:            Created 
Info:        Working on 1424
Info:            Created 
Info:        Working on 2192
Info:            Created 
Info:        Working on 2513
Info:            Created 
Info:        Working on 1765
Info:            Created 
Info:        Working on 2411
Info:            Created 
Info:        Working on 2666
Info:            Created 
Info:        Working on 2080
Info:            Created 
Info:        Working on 2581
Info:            Created 
Info:        Working on 2805
Info:            Created 
Info:        Working on 2334
Info:            Created 
Info:        Working on 2725
Info:            Created 
Info:        Working on 2937
Info:            Created 
Info:        Working on 2528
Info:            Created 
Info:        Working on 2860
Info:            Created 
Info:        Working on 3052
Info:            Created 
Info:        Working on 2681
Info:            Created 
Info:        Working on 2986
Info:            Created 
Info:        Working on 3137
Info:            Created 
Info:        Working on 2820
Info:            Created 
Info:        Working on 2990
Info:            Created 
Info:        Working on 3136
Info:            Created 
Info:        Working on 2952
Info:            Created 
Info:        Working on 2871
Info:            Created 
Info:        Working on 3048
Info:            Created 
Info:        Working on 3065
Info:            Created 
Info:        Working on 2738
Info:            Created 
Info:        Working on 2931
Info:            Created 
Info:        Working on 2994
Info:            Created 
Info:        Working on 2595
Info:            Created 
Info:        Working on 2798
Info:            Created 
Info:        Working on 2875
Info:            Created 
Info:        Working on 2425
Info:            Created 
Info:        Working on 2659
Info:            Created 
Info:        Working on 2742
Info:            Created 
Info:        Working on 2206
Info:            Created 
Info:        Working on 2506
Info:            Created 
Info:        Working on 2599
Info:            Created 
Info:        Working on 1927
Info:            Created 
Info:        Working on 2312
Info:            Created 
Info:        Working on 2429
Info:            Created 
Info:        Working on 1603
Info:            Created 
Info:        Working on 2058
Info:            Created 
Info:        Working on 2210
Info:            Created 
Info:        Working on 1269
Info:            Created 
Info:        Working on 1743
Info:            Created 
Info:        Working on 1931
Info:            Created 
Info:        Working on 959
Info:            Created 
Info:        Working on 1402
Info:            Created 
Info:        Working on 1607
Info:            Created 
Info:        Working on 690
Info:            Created 
Info:        Working on 1079
Info:            Created 
Info:        Working on 1273
Info:            Created 
Info:        Working on 477
Info:            Created 
Info:        Working on 793
Info:            Created 
Info:        Working on 963
Info:            Created 
Info:        Working on 694
Info:            Created 
Info:        Working on 454
Info:            Created 
Info:        Working on 455
Info:            Created 
Info:        Working on 786
Info:            Created 
Info:        Working on 785
Info:            Created 
Info:        Working on 666
Info:            Created 
Info:        Working on 648
Info:            Created 
Info:        Working on 1072
Info:            Created 
Info:        Working on 919
Info:            Created 
Info:        Working on 915
Info:            Created 
Info:        Working on 1395
Info:            Created 
Info:        Working on 1229
Info:            Created 
Info:        Working on 1225
Info:            Created 
Info:        Working on 1736
Info:            Created 
Info:        Working on 1563
Info:            Created 
Info:        Working on 1559
Info:            Created 
Info:        Working on 2051
Info:            Created 
Info:        Working on 1887
Info:            Created 
Info:        Working on 1883
Info:            Created 
Info:        Working on 2305
Info:            Created 
Info:        Working on 2166
Info:            Created 
Info:        Working on 2162
Info:            Created 
Info:        Working on 2499
Info:            Created 
Info:        Working on 2385
Info:            Created 
Info:        Working on 2381
Info:            Created 
Info:        Working on 2652
Info:            Created 
Info:        Working on 2555
Info:            Created 
Info:        Working on 2551
Info:            Created 
Info:        Working on 2791
Info:            Created 
Info:        Working on 2699
Info:            Created 
Info:        Working on 2695
Info:            Created 
Info:        Working on 2924
Info:            Created 
Info:        Working on 2836
Info:            Created 
Info:        Working on 2832
Info:            Created 
Info:        Working on 3042
Info:            Created 
Info:        Working on 2967
Info:            Created 
Info:        Working on 2963
Info:            Created 
Info:        Working on 3133
Info:            Created 
Info:        Working on 3077
Info:            Created 
Info:        Working on 3073
Info:            Created 
Info:        Working on 3196
Info:            Created 
Info:        Working on 3153
Info:            Created 
Info:        Working on 3080
Info:            Created 
Info:        Working on 3195
Info:            Created 
Info:        Working on 3209
Info:            Created 
Info:        Working on 2976
Info:            Created 
Info:        Working on 3129
Info:            Created 
Info:        Working on 3157
Info:            Created 
Info:        Working on 2847
Info:            Created 
Info:        Working on 3036
Info:            Created 
Info:        Working on 3084
Info:            Created 
Info:        Working on 2711
Info:            Created 
Info:        Working on 2917
Info:            Created 
Info:        Working on 2980
Info:            Created 
Info:        Working on 2567
Info:            Created 
Info:        Working on 2784
Info:            Created 
Info:        Working on 2851
Info:            Created 
Info:        Working on 2397
Info:            Created 
Info:        Working on 2645
Info:            Created 
Info:        Working on 2715
Info:            Created 
Info:        Working on 2178
Info:            Created 
Info:        Working on 2492
Info:            Created 
Info:        Working on 2571
Info:            Created 
Info:        Working on 1899
Info:            Created 
Info:        Working on 2298
Info:            Created 
Info:        Working on 2401
Info:            Created 
Info:        Working on 1575
Info:            Created 
Info:        Working on 2044
Info:            Created 
Info:        Working on 2182
Info:            Created 
Info:        Working on 1241
Info:            Created 
Info:        Working on 1729
Info:            Created 
Info:        Working on 1903
Info:            Created 
Info:        Working on 931
Info:            Created 
Info:        Working on 1388
Info:            Created 
Info:        Working on 1579
Info:            Created 
Info:        Working on 660
Info:            Created 
Info:        Working on 1065
Info:            Created 
Info:        Working on 1245
Info:            Created 
Info:        Working on 935
Info:            Created 
Info:        Working on 635
Info:            Created 
Info:        Working on 636
Info:            Created 
Info:        Working on 1058
Info:            Created 
Info:        Working on 1057
Info:            Created 
Info:        Working on 903
Info:            Created 
Info:        Working on 886
Info:            Created 
Info:        Working on 1381
Info:            Created 
Info:        Working on 1200
Info:            Created 
Info:        Working on 1196
Info:            Created 
Info:        Working on 1722
Info:            Created 
Info:        Working on 1540
Info:            Created 
Info:        Working on 1536
Info:            Created 
Info:        Working on 2037
Info:            Created 
Info:        Working on 1867
Info:            Created 
Info:        Working on 1543
Info:            Created 
Info:        Working on 2036
Info:            Created 
Info:        Working on 2150
Info:            Created 
Info:        Working on 1209
Info:            Created 
Info:        Working on 1718
Info:            Created 
Info:        Working on 1871
Info:            Created 
Info:        Working on 897
Info:            Created 
Info:        Working on 1375
Info:            Created 
Info:        Working on 1547
Info:            Created 
Info:        Working on 1213
Info:            Created 
Info:        Working on 873
Info:            Created 
Info:        Working on 874
Info:            Created 
Info:        Working on 1368
Info:            Created 
Info:        Working on 1367
Info:            Created 
Info:        Working on 1185
Info:            Created 
Info:        Working on 1168
Info:            Created 
Info:        Working on 1712
Info:            Created 
Info:        Working on 1515
Info:            Created 
Info:        Working on 1511
Info:            Created 
Info:        Working on 2033
Info:            Created 
Info:        Working on 1855
Info:            Created 
Info:        Working on 1851
Info:            Created 
Info:        Working on 2291
Info:            Created 
Info:        Working on 2144
Info:            Created 
Info:        Working on 1858
Info:            Created 
Info:        Working on 2290
Info:            Created 
Info:        Working on 2369
Info:            Created 
Info:        Working on 1524
Info:            Created 
Info:        Working on 2029
Info:            Created 
Info:        Working on 2148
Info:            Created 
Info:        Working on 1179
Info:            Created 
Info:        Working on 1706
Info:            Created 
Info:        Working on 1862
Info:            Created 
Info:        Working on 1528
Info:            Created 
Info:        Working on 1155
Info:            Created 
Info:        Working on 1156
Info:            Created 
Info:        Working on 1699
Info:            Created 
Info:        Working on 1698
Info:            Created 
Info:        Working on 1500
Info:            Created 
Info:        Working on 1483
Info:            Created 
Info:        Working on 2023
Info:            Created 
Info:        Working on 1830
Info:            Created 
Info:        Working on 1826
Info:            Created 
Info:        Working on 2287
Info:            Created 
Info:        Working on 2132
Info:            Created 
Info:        Working on 2128
Info:            Created 
Info:        Working on 2485
Info:            Created 
Info:        Working on 2363
Info:            Created 
Info:        Working on 2135
Info:            Created 
Info:        Working on 2484
Info:            Created 
Info:        Working on 2539
Info:            Created 
Info:        Working on 1839
Info:            Created 
Info:        Working on 2283
Info:            Created 
Info:        Working on 2367
Info:            Created 
Info:        Working on 1494
Info:            Created 
Info:        Working on 2017
Info:            Created 
Info:        Working on 2139
Info:            Created 
Info:        Working on 1843
Info:            Created 
Info:        Working on 1470
Info:            Created 
Info:        Working on 1471
Info:            Created 
Info:        Working on 2010
Info:            Created 
Info:        Working on 2009
Info:            Created 
Info:        Working on 1815
Info:            Created 
Info:        Working on 1798
Info:            Created 
Info:        Working on 2277
Info:            Created 
Info:        Working on 2107
Info:            Created 
Info:        Working on 2103
Info:            Created 
Info:        Working on 2481
Info:            Created 
Info:        Working on 2351
Info:            Created 
Info:        Working on 2347
Info:            Created 
Info:        Working on 2638
Info:            Created 
Info:        Working on 2533
Info:            Created 
Info:        Working on 2354
Info:            Created 
Info:        Working on 2637
Info:            Created 
Info:        Working on 2683
Info:            Created 
Info:        Working on 2116
Info:            Created 
Info:        Working on 2477
Info:            Created 
Info:        Working on 2537
Info:            Created 
Info:        Working on 1809
Info:            Created 
Info:        Working on 2271
Info:            Created 
Info:        Working on 2358
Info:            Created 
Info:        Working on 2120
Info:            Created 
Info:        Working on 2264
Info:            Created 
Info:        Working on 1786
Info:            Created 
Info:        Working on 2092
Info:            Created 
Info:        Working on 2471
Info:            Created 
Info:        Working on 2089
Info:            Created 
Info:        Working on 2339
Info:            Created 
Info:        Working on 504
Info:            Created 
Info:        Working on 505
Info:            Created 
Info:        Working on 998
Info:            Created 
Info:        Working on 811
Info:            Created 
Info:        Working on 726
Info:            Created 
Info:        Working on 719
Info:            Created 
Info:        Working on 1308
Info:            Created 
Info:        Working on 997
Info:            Created 
Info:        Working on 992
Info:            Created 
Info:        Working on 1642
Info:            Created 
Info:        Working on 1307
Info:            Created 
Info:        Working on 1302
Info:            Created 
Info:        Working on 1966
Info:            Created 
Info:        Working on 1641
Info:            Created 
Info:        Working on 1636
Info:            Created 
Info:        Working on 2245
Info:            Created 
Info:        Working on 1965
Info:            Created 
Info:        Working on 1960
Info:            Created 
Info:        Working on 2464
Info:            Created 
Info:        Working on 2244
Info:            Created 
Info:        Working on 2239
Info:            Created 
Info:        Working on 2634
Info:            Created 
Info:        Working on 2463
Info:            Created 
Info:        Working on 2458
Info:            Created 
Info:        Working on 2777
Info:            Created 
Info:        Working on 2633
Info:            Created 
Info:        Working on 2628
Info:            Created 
Info:        Working on 2910
Info:            Created 
Info:        Working on 2776
Info:            Created 
Info:        Working on 2771
Info:            Created 
Info:        Working on 3029
Info:            Created 
Info:        Working on 2909
Info:            Created 
Info:        Working on 2904
Info:            Created 
Info:        Working on 3123
Info:            Created 
Info:        Working on 3028
Info:            Created 
Info:        Working on 3023
Info:            Created 
Info:        Working on 3192
Info:            Created 
Info:        Working on 3122
Info:            Created 
Info:        Working on 3117
Info:            Created 
Info:        Working on 3244
Info:            Created 
Info:        Working on 3191
Info:            Created 
Info:        Working on 3186
Info:            Created 
Info:        Working on 3290
Info:            Created 
Info:        Working on 3243
Info:            Created 
Info:        Working on 3238
Info:            Created 
Info:        Working on 3336
Info:            Created 
Info:        Working on 3289
Info:            Created 
Info:        Working on 3284
Info:            Created 
Info:        Working on 3382
Info:            Created 
Info:        Working on 3335
Info:            Created 
Info:        Working on 3330
Info:            Created 
Info:        Working on 3428
Info:            Created 
Info:        Working on 3381
Info:            Created 
Info:        Working on 3376
Info:            Created 
Info:        Working on 3474
Info:            Created 
Info:        Working on 3427
Info:            Created 
Info:        Working on 3422
Info:            Created 
Info:        Working on 3520
Info:            Created 
Info:        Working on 3473
Info:            Created 
Info:        Working on 3468
Info:            Created 
Info:        Working on 3566
Info:            Created 
Info:        Working on 3519
Info:            Created 
Info:        Working on 3514
Info:            Created 
Info:        Working on 3612
Info:            Created 
Info:        Working on 3565
Info:            Created 
Info:        Working on 3560
Info:            Created 
Info:        Working on 3658
Info:            Created 
Info:        Working on 3611
Info:            Created 
Info:        Working on 3606
Info:            Created 
Info:        Working on 3704
Info:            Created 
Info:        Working on 3657
Info:            Created 
Info:        Working on 3652
Info:            Created 
Info:        Working on 3750
Info:            Created 
Info:        Working on 3703
Info:            Created 
Info:        Working on 3698
Info:            Created 
Info:        Working on 3796
Info:            Created 
Info:        Working on 3749
Info:            Created 
Info:        Working on 3744
Info:            Created 
Info:        Working on 3842
Info:            Created 
Info:        Working on 3795
Info:            Created 
Info:        Working on 3790
Info:            Created 
Info:        Working on 3888
Info:            Created 
Info:        Working on 3841
Info:            Created 
Info:        Working on 3836
Info:            Created 
Info:        Working on 3934
Info:            Created 
Info:        Working on 3887
Info:            Created 
Info:        Working on 3882
Info:            Created 
Info:        Working on 3980
Info:            Created 
Info:        Working on 3933
Info:            Created 
Info:        Working on 3928
Info:            Created 
Info:        Working on 4026
Info:            Created 
Info:        Working on 3979
Info:            Created 
Info:        Working on 3974
Info:            Created 
Info:        Working on 4072
Info:            Created 
Info:        Working on 4025
Info:            Created 
Info:        Working on 4020
Info:            Created 
Info:        Working on 4118
Info:            Created 
Info:        Working on 4071
Info:            Created 
Info:        Working on 4066
Info:            Created 
Info:        Working on 4164
Info:            Created 
Info:        Working on 4117
Info:            Created 
Info:        Working on 4112
Info:            Created 
Info:        Working on 4210
Info:            Created 
Info:        Working on 4163
Info:            Created 
Info:        Working on 4158
Info:            Created 
Info:        Working on 4256
Info:            Created 
Info:        Working on 4209
Info:            Created 
Info:        Working on 4204
Info:            Created 
Info:        Working on 4302
Info:            Created 
Info:        Working on 4255
Info:            Created 
Info:        Working on 4250
Info:            Created 
Info:        Working on 4348
Info:            Created 
Info:        Working on 4301
Info:            Created 
Info:        Working on 4296
Info:            Created 
Info:        Working on 4394
Info:            Created 
Info:        Working on 4347
Info:            Created 
Info:        Working on 4342
Info:            Created 
Info:        Working on 4440
Info:            Created 
Info:        Working on 4393
Info:            Created 
Info:        Working on 4388
Info:            Created 
Info:        Working on 4486
Info:            Created 
Info:        Working on 4439
Info:            Created 
Info:        Working on 4434
Info:            Created 
Info:        Working on 4532
Info:            Created 
Info:        Working on 4485
Info:            Created 
Info:        Working on 4480
Info:            Created 
Info:        Working on 4578
Info:            Created 
Info:        Working on 4531
Info:            Created 
Info:        Working on 4526
Info:            Created 
Info:        Working on 4624
Info:            Created 
Info:        Working on 4577
Info:            Created 
Info:        Working on 4572
Info:            Created 
Info:        Working on 4670
Info:            Created 
Info:        Working on 4623
Info:            Created 
Info:        Working on 4618
Info:            Created 
Info:        Working on 4716
Info:            Created 
Info:        Working on 4669
Info:            Created 
Info:        Working on 4664
Info:            Created 
Info:        Working on 4762
Info:            Created 
Info:        Working on 4715
Info:            Created 
Info:        Working on 4710
Info:            Created 
Info:        Working on 4808
Info:            Created 
Info:        Working on 4761
Info:            Created 
Info:        Working on 4756
Info:            Created 
Info:        Working on 4854
Info:            Created 
Info:        Working on 4807
Info:            Created 
Info:        Working on 4802
Info:            Created 
Info:        Working on 4900
Info:            Created 
Info:        Working on 4853
Info:            Created 
Info:        Working on 4848
Info:            Created 
Info:        Working on 4946
Info:            Created 
Info:        Working on 4899
Info:            Created 
Info:        Working on 4894
Info:            Created 
Info:        Working on 4992
Info:            Created 
Info:        Working on 4945
Info:            Created 
Info:        Working on 4940
Info:            Created 
Info:        Working on 5037
Info:            Created 
Info:        Working on 4991
Info:            Created 
Info:        Working on 4986
Info:            Created 
Info:        Working on 5079
Info:            Created 
Info:        Working on 5036
Info:            Created 
Info:        Working on 5031
Info:            Created 
Info:        Working on 5111
Info:            Created 
Info:        Working on 5078
Info:            Created 
Info:        Working on 5073
Info:            Created 
Info:        Working on 5128
Info:            Created 
Info:        Working on 5110
Info:            Created 
Info:        Working on 5105
Info:            Created 
Info:        Working on 5131
Info:            Created 
Info:        Working on 5127
Info:            Created 
Info:        Working on 5097
Info:            Created 
Info:        Working on 5118
Info:            Created 
Info:        Working on 5133
Info:            Created 
Info:        Working on 5059
Info:            Created 
Info:        Working on 5089
Info:            Created 
Info:        Working on 5123
Info:            Created 
Info:        Working on 5015
Info:            Created 
Info:        Working on 5048
Info:            Created 
Info:        Working on 5101
Info:            Created 
Info:        Working on 4969
Info:            Created 
Info:        Working on 5003
Info:            Created 
Info:        Working on 5063
Info:            Created 
Info:        Working on 4923
Info:            Created 
Info:        Working on 4957
Info:            Created 
Info:        Working on 5019
Info:            Created 
Info:        Working on 4877
Info:            Created 
Info:        Working on 4911
Info:            Created 
Info:        Working on 4973
Info:            Created 
Info:        Working on 4831
Info:            Created 
Info:        Working on 4865
Info:            Created 
Info:        Working on 4927
Info:            Created 
Info:        Working on 4785
Info:            Created 
Info:        Working on 4819
Info:            Created 
Info:        Working on 4881
Info:            Created 
Info:        Working on 4739
Info:            Created 
Info:        Working on 4773
Info:            Created 
Info:        Working on 4835
Info:            Created 
Info:        Working on 4693
Info:            Created 
Info:        Working on 4727
Info:            Created 
Info:        Working on 4789
Info:            Created 
Info:        Working on 4647
Info:            Created 
Info:        Working on 4681
Info:            Created 
Info:        Working on 4743
Info:            Created 
Info:        Working on 4601
Info:            Created 
Info:        Working on 4635
Info:            Created 
Info:        Working on 4697
Info:            Created 
Info:        Working on 4555
Info:            Created 
Info:        Working on 4589
Info:            Created 
Info:        Working on 4651
Info:            Created 
Info:        Working on 4509
Info:            Created 
Info:        Working on 4543
Info:            Created 
Info:        Working on 4605
Info:            Created 
Info:        Working on 4463
Info:            Created 
Info:        Working on 4497
Info:            Created 
Info:        Working on 4559
Info:            Created 
Info:        Working on 4417
Info:            Created 
Info:        Working on 4451
Info:            Created 
Info:        Working on 4513
Info:            Created 
Info:        Working on 4371
Info:            Created 
Info:        Working on 4405
Info:            Created 
Info:        Working on 4467
Info:            Created 
Info:        Working on 4325
Info:            Created 
Info:        Working on 4359
Info:            Created 
Info:        Working on 4421
Info:            Created 
Info:        Working on 4279
Info:            Created 
Info:        Working on 4313
Info:            Created 
Info:        Working on 4375
Info:            Created 
Info:        Working on 4233
Info:            Created 
Info:        Working on 4267
Info:            Created 
Info:        Working on 4329
Info:            Created 
Info:        Working on 4187
Info:            Created 
Info:        Working on 4221
Info:            Created 
Info:        Working on 4283
Info:            Created 
Info:        Working on 4141
Info:            Created 
Info:        Working on 4175
Info:            Created 
Info:        Working on 4237
Info:            Created 
Info:        Working on 4095
Info:            Created 
Info:        Working on 4129
Info:            Created 
Info:        Working on 4191
Info:            Created 
Info:        Working on 4049
Info:            Created 
Info:        Working on 4083
Info:            Created 
Info:        Working on 4145
Info:            Created 
Info:        Working on 4003
Info:            Created 
Info:        Working on 4037
Info:            Created 
Info:        Working on 4099
Info:            Created 
Info:        Working on 3957
Info:            Created 
Info:        Working on 3991
Info:            Created 
Info:        Working on 4053
Info:            Created 
Info:        Working on 3911
Info:            Created 
Info:        Working on 3945
Info:            Created 
Info:        Working on 4007
Info:            Created 
Info:        Working on 3865
Info:            Created 
Info:        Working on 3899
Info:            Created 
Info:        Working on 3961
Info:            Created 
Info:        Working on 3819
Info:            Created 
Info:        Working on 3853
Info:            Created 
Info:        Working on 3915
Info:            Created 
Info:        Working on 3773
Info:            Created 
Info:        Working on 3807
Info:            Created 
Info:        Working on 3869
Info:            Created 
Info:        Working on 3727
Info:            Created 
Info:        Working on 3761
Info:            Created 
Info:        Working on 3823
Info:            Created 
Info:        Working on 3681
Info:            Created 
Info:        Working on 3715
Info:            Created 
Info:        Working on 3777
Info:            Created 
Info:        Working on 3635
Info:            Created 
Info:        Working on 3669
Info:            Created 
Info:        Working on 3731
Info:            Created 
Info:        Working on 3589
Info:            Created 
Info:        Working on 3623
Info:            Created 
Info:        Working on 3685
Info:            Created 
Info:        Working on 3543
Info:            Created 
Info:        Working on 3577
Info:            Created 
Info:        Working on 3639
Info:            Created 
Info:        Working on 3497
Info:            Created 
Info:        Working on 3531
Info:            Created 
Info:        Working on 3593
Info:            Created 
Info:        Working on 3451
Info:            Created 
Info:        Working on 3485
Info:            Created 
Info:        Working on 3547
Info:            Created 
Info:        Working on 3405
Info:            Created 
Info:        Working on 3439
Info:            Created 
Info:        Working on 3501
Info:            Created 
Info:        Working on 3359
Info:            Created 
Info:        Working on 3393
Info:            Created 
Info:        Working on 3455
Info:            Created 
Info:        Working on 3313
Info:            Created 
Info:        Working on 3347
Info:            Created 
Info:        Working on 3409
Info:            Created 
Info:        Working on 3267
Info:            Created 
Info:        Working on 3301
Info:            Created 
Info:        Working on 3363
Info:            Created 
Info:        Working on 3221
Info:            Created 
Info:        Working on 3255
Info:            Created 
Info:        Working on 3317
Info:            Created 
Info:        Working on 3169
Info:            Created 
Info:        Working on 3207
Info:            Created 
Info:        Working on 3271
Info:            Created 
Info:        Working on 3100
Info:            Created 
Info:        Working on 3148
Info:            Created 
Info:        Working on 3225
Info:            Created 
Info:        Working on 3006
Info:            Created 
Info:        Working on 3063
Info:            Created 
Info:        Working on 3173
Info:            Created 
Info:        Working on 2887
Info:            Created 
Info:        Working on 2948
Info:            Created 
Info:        Working on 3104
Info:            Created 
Info:        Working on 2754
Info:            Created 
Info:        Working on 2816
Info:            Created 
Info:        Working on 3010
Info:            Created 
Info:        Working on 2611
Info:            Created 
Info:        Working on 2677
Info:            Created 
Info:        Working on 2891
Info:            Created 
Info:        Working on 2441
Info:            Created 
Info:        Working on 2524
Info:            Created 
Info:        Working on 2758
Info:            Created 
Info:        Working on 2222
Info:            Created 
Info:        Working on 2330
Info:            Created 
Info:        Working on 2615
Info:            Created 
Info:        Working on 1943
Info:            Created 
Info:        Working on 2076
Info:            Created 
Info:        Working on 2445
Info:            Created 
Info:        Working on 1619
Info:            Created 
Info:        Working on 1761
Info:            Created 
Info:        Working on 2226
Info:            Created 
Info:        Working on 1285
Info:            Created 
Info:        Working on 1420
Info:            Created 
Info:        Working on 1947
Info:            Created 
Info:        Working on 975
Info:            Created 
Info:        Working on 1097
Info:            Created 
Info:        Working on 1623
Info:            Created 
Info:        Working on 706
Info:            Created 
Info:        Working on 812
Info:            Created 
Info:        Working on 1289
Info:            Created 
Info:        Working on 979
Info:            Created 
Info:        Working on 193
Info:            Created 
Info:        Working on 112
Info:            Created 
Info:        Created 
Info:    Working on BRep 0
Info:        Using 3D tolerance 0.000601806
Info:        Using 3D tolerance 1e-06
Info:        Created BRep 
Info:    Finished with 
Info:    Points:                 0 found       0 created       0 failed
Info:    Coordinate Systems      0 found       0 created       0 failed
Info:    Curves:                 0 found       0 created       0 failed
Info:    Surfaces:               0 found       0 created       0 failed
Info:    Trimmed Surfaces:       0 found       0 created       0 failed
Info:    Breps:                  1 found       1 created       0 failed
Finished logging messages at Sun Sep 24 18:18:47 2023
